services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hockey-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - hockey_sql_data:/var/opt/mssql

volumes:
  hockey_sql_data: