services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hockey-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - hockey_sql_data:/var/opt/mssql
    env_file:
      - ../.env

volumes:
  hockey_sql_data:
    name: hockeylytics_hockey_sql_data
    external: True
